# +-------------------------+
# | +---------------------+ |
# | |    Enchantments+-   | |
# | +---------------------+ |
# +-------------------------+
#                                                                                     -#-
# This is the configuration file for Enchantments+-.
# Need help? Check the GitHub wiki: https://github.com/dsdd/EnchantmentsPlusMinus
#
# +------------------------+
# |                        |
# |     Configuration      |
# |                        |
# +------------------------+
#        
# Enchant configuration has been moved to the /enchants/ folder!
#                                                                             -#-

auto-update: true
show-enchant-lore: true
use-roman-numerals: false
open-enchant-gui-on-right-click: true
applyfortuneon: 
  - COAL
  - LAPIS_LAZULI
  - REDSTONE
  - DIAMOND  
  - EMERALD
  - QUARTZ
playerkilltokens: 
  enabled: true
  min: 25
  max: 50
mobkilltokens:
  enabled: true
  min: 5
  max: 10
miningtokens:
  enabled: true
  min: 25
  max: 50
  blockstobreak: 1000
