# +-------------------------+
# | +---------------------+ |
# | |    Enchantments+-   | |
# | +---------------------+ |
# +-------------------------+
#                                                                                     -#-
# This is the configuration file for Enchantments+-.
# Need help? Check the GitHub wiki: https://github.com/dsdd/EnchantmentsPlusMinus
#
# +------------------------+
# |                        |
# |     Configuration      |
# |                        |
# +------------------------+
#        
# Enchant configuration has been moved to the /enchants/ folder!
#                                                                             -#-

auto-update: true
show-enchant-lore: true
use-roman-numerals: false
    
guis:
  examplegui:
    enchants:
    - depth_strider
    items:
    - BEDROCK
  pickaxe:
    enchants:
    - efficiency
    - unbreaking
    - fortune
    - mending
    - haste
    - explosive
    - excavate
    - diamond
    - autosmelt
    - telepathy
    - tokenblocks
    - tokencharity
    items:
    - WOODEN_PICKAXE
    - STONE_PICKAXE
    - IRON_PICKAXE
    - GOLDEN_PICKAXE
    - DIAMOND_PICKAXE
    - NETHERITE_PICKAXE
  sword:
    enchants:
    - sharpness
    - unbreaking
    - fire_aspect
    - mending
    - jagged
    - retaliate
    - lifesteal
    - momentum
    - beheading
    - last_resort
    items:
    - WOODEN_SWORD
    - STONE_SWORD
    - IRON_SWORD
    - GOLDEN_SWORD
    - DIAMOND_SWORD
    - NETHERITE_SWORD
  axe:
    enchants:
    - sharpness
    - unbreaking
    - mending
    - efficiency
    - retaliate
    - beheading
    items:
    - WOODEN_AXE
    - STONE_AXE
    - IRON_AXE
    - GOLDEN_AXE
    - DIAMOND_AXE
    - NETHERITE_AXE
  shovel:
    enchants:
    - efficiency
    - unbreaking
    - mending
    items:
    - WOODEN_SHOVEL
    - STONE_SHOVEL
    - IRON_SHOVEL
    - GOLDEN_SHOVEL
    - DIAMOND_SHOVEL
    - NETHERITE_SHOVEL
  hoe:
    enchants:
    - unbreaking
    - mending
    items:
    - WOODEN_HOE
    - STONE_HOE
    - IRON_HOE
    - GOLDEN_HOE
    - DIAMOND_HOE
    - NETHERITE_HOE
  armor:
    enchants:
    - protection
    - unbreaking
    - poisonous
    - volcanic
    - saturated
    - insatiable
    - stiffen
    items:
    - LEATHER_HELMET
    - LEATHER_CHESTPLATE
    - LEATHER_LEGGINGS
    - LEATHER_BOOTS
    - CHAINMAIL_HELMET
    - CHAINMAIL_CHESTPLATE
    - CHAINMAIL_LEGGINGS
    - CHAINMAIL_BOOTS
    - GOLDEN_HELMET
    - GOLDEN_CHESTPLATE
    - GOLDEN_LEGGINGS
    - GOLDEN_BOOTS
    - IRON_HELMET
    - IRON_CHESTPLATE
    - IRON_LEGGINGS
    - IRON_BOOTS
    - DIAMOND_HELMET
    - DIAMOND_CHESTPLATE
    - DIAMOND_LEGGINGS
    - DIAMOND_BOOTS
    - NETHERITE_HELMET
    - NETHERITE_CHESTPLATE
    - NETHERITE_LEGGINGS
    - NETHERITE_BOOTS
        
misc:
  applyfortuneon: 
    - COAL
    - LAPIS_LAZULI
    - REDSTONE
    - DIAMOND
    - EMERALD
    - QUARTZ
  playerkilltokens:
    enabled: true
    min: 25
    max: 50
  mobkilltokens:
    enabled: true
    min: 5
    max: 10
  miningtokens:
    enabled: true
    min: 25
    max: 50
    blockstobreak: 1000
